if: |
  commit_message =~ /^Build.*:/

os: linux

dist: xenial

language: shell

git:
  depth: 2

services:
  - docker

env:
  global:
    - DOCKER_ORG=provarepro
    - DOCKER_USER=reprova
    # DOCKER_PASS="..."
    - secure: "AKk0amWRuQIAaW//sTsJwdYtyWoiH+ZUyen9mMXBfybDtb7VwT2n1XT3T/AmSbJY+bkoJl57R8fhNPGRhjztackFU+TValOt7sufTZf1+zXkGHwgSx9b1D/BuSs1Yd4cL37qcbkDcorFTc9KTlJlF4bXA3Ktbk4P3E3EC9XVIMUZ48brA2h9cCKedy6KMcOV1cMX081+nd9AIEG49OjOZRR5+RxhMeDjXwd9eGXnLXdI9IPTDiNiCBaMFemkU+hLhmfZCbpGjAAsZdGF0G0D2k3vfjWYseldJpgZ0YB/DYPQiuTHbgU7INTdgRsobcfRiPwgfIKOMDv2qQh6k07KBmu9vnindMi8Bz3WnL0HYuhYcH84LD6WyCg1TFiIu7gkKB+2APqLAYNAdBSPvET1T+MWcLUtcsSy17eCijMC0pg6WYfRuI90GM898pcQgzFxiFAxNXylKosO0Jkc6j0q9loW6oKMHHbP6ODhET2CLFNgamL1YLOr+wGMfi57n4io3gBzH6nspriiceylxB/xY5a4Z/KG7ct5wXoNqQw3+LMgijJ4tKbRllOoP0rWJu9Zkx+Q4Krt4uB5Xjtb8PUkyF5acY7lj7sA9wpGjVWHWlRZ901PunulYAsSegeWIAJDFToWXGKqIeefPJ1Eqo1HkE/D9C1OB/A6MjKG4ODyzFI="

jobs:
  include:
    - stage: build docker image
      if: |
        commit_message =~ /^Build docker:*/
      script: |
        SW_NAME=`echo ${TRAVIS_REPO_SLUG##*/} | sed 's/ *$//g'`
        DOCKER_SW_NAME=${SW_NAME,,}
        SW_TAG=${TRAVIS_COMMIT_MESSAGE#*"Build docker:"}
        SW_TAG=`echo ${SW_TAG%%,*} | sed 's/ *$//g'`
        
        IMAGE_NAME="${DOCKER_ORG}/${DOCKER_SW_NAME}:${SW_TAG}"

        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

        docker pull ${IMAGE_NAME} || true

        docker build\
          --label "BUILT-BY=Travis"\
          --label "BUILT-FROM=${TRAVIS_REPO_SLUG}"\
          --label "BUILD-LOG=${TRAVIS_BUILD_WEB_URL}"\
          --tag ${IMAGE_NAME}\
          ./${SW_TAG}

        docker images

        docker push ${IMAGE_NAME}

